# Display configuration
screen_duration: 5  # seconds between screen switches
network_interface: eth0
invert_duration: 30
day_start_hour: 8
night_start_hour: 17

screens:
  - name: Time
    components:
      - type: time
        x: 5
        y: 12
        label: Time
        time_format: "15:04:05"  # 24-hour format with seconds

      - type: time
        x: 5
        y: 25
        label: Date
        time_format: "Mon 02-Jan"   # date format

  - name: System Status
    components:
      - type: ip
        x: 5
        y: 12
        label: IP

      - type: cpu
        x: 5
        y: 23
        label: CPU
        show_bar: true
        bar_width: 88

      - type: memory
        x: 5
        y: 50
        label: MEM
        show_bar: true
        bar_width: 88

  - name: Storage
    components:
      - type: disk
        x: 5
        y: 20
        label: Disk
        show_bar: true
        bar_width: 118

